version: "3"
services:
  redis:
    image: redis
    container_name: redis
    ports:
      - 6741:6739
    volumes:
      - ./backend/config/redis-prod.conf:/redis.conf
    command: ["redis-server", "/redis.conf"]

  proxy:
    container_name: proxy
    build: ./proxy/http
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend

  backend:
    container_name: poke-search-server
    build: ./backend
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - redis

  frontend:
    container_name: poke-search-app
    build: ./frontend
    restart: unless-stopped
    ports:
      - 8081:80

volumes:
  redis-volume:
    external: false
