version: "3"
services:
  redis-local-dev:
    image: redis
    container_name: redis-local-dev
    ports:
      - 6740:6739
    volumes:
      - ./backend/config/redis-dev.conf:/redis.conf
      - redis-volume:/data
    command: ["redis-server", "/redis.conf"]

volumes:
  redis-volume:
    external: false
